# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ExchangeRates' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExchangeRates
pod 'Alamofire'
pod 'Kingfisher'
pod 'R.swift'
pod 'SnapKit'
pod 'Moya'
pod 'SwiftyJSON'
pod 'ReachabilitySwift'
pod 'ActiveLabel'
pod 'SCLAlertView'
end
